main_file: "Meditadaze"

midi_controllers:

 Master_Volume:
  midi_cc: 7
  value: 65
 Start:
  midi_cc: 114
  value: '0'
  labels: [ '0', '1' ]
 Stop:
  midi_cc: 19
  value: '0'
  labels: [ '0', '1' ]
 Slowness:
  midi_cc: 18
  value: 0 
 
 Seed:
  midi_cc: 16
  value: 0