
main_file: "main.pd"

midi_controllers:
 volume:
  midi_cc: 7
  value: 64
 metro:
  midi_cc: 4
  value: 50
 random_1:
  midi_cc: 2
  value: 30
 random_2:
  midi_cc: 3
  value: 70
 freeze_verb:
  midi_cc: 1
  value: 80
