
main_file: "2oscringnoise1.pd"

midi_controllers:
 volume:
  midi_cc: 7
  value: 64
 program:
  midi_cc: 2
  value: '1'
  labels: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16']
 param 1: 70
 param 2: 71
 param 3: 72
 param 4: 73
 param 5: 74
 param 6: 75
 param 7: 76
 param 8: 77
 param 9: 78
 param 10: 79
 param 11: 80
 param 12: 81
 
