main_file: "PunchyRhodeyFX"

midi_controllers:
 Master_Volume:
  midi_cc: 7
  value: 85
 Room Size:
  midi_cc: 93
  value: 0
 Wet Dry:
  midi_cc: 73
  value: 0
 Damp:
  midi_cc: 75
  value: 0
  value: 25

 Tone:
  midi_cc: 74
  value: 67 
 Modulation:
  midi_cc: 71
  value: 50
 Decay:
  midi_cc: 76 
  value: 0
 Transpose:
  midi_cc: 77
  value: 0
    
 Tempo:
  midi_cc: 18
  value: 32
 Velocity:
  midi_cc: 19
  value: 127
 Swing:
  midi_cc: 16
  value: 0
 Note Length:
  midi_cc: 17
  value: 28
  
 Play Rec Loop:
  midi_cc: 114
  value: '0'
  labels: [ '0', '1', '2']
 Mode:
  midi_cc: 72
  value: '1'
  labels: [ '0', '1']