main_file: "Zynth_A_Sketch"

midi_controllers:
 Erase:
  midi_cc: 74
  value: 50
 X Draw:
  midi_cc: 114
  value: 0 
 Brush Size:
  midi_cc: 19
  value: 4
 Y Draw:
  midi_cc: 18
  value: 0

 Red:
  midi_cc: 93
  value: 60
 Green:
  midi_cc: 73
  value: 60
 Blue:
  midi_cc: 75
  value: 60
 N A:
  midi_cc: 99
  value: 0
  
 Window Size:
  midi_cc: 71
  value: 10
 Window X Pos:
  midi_cc: 76
  value: 40
 Window Y Pos:
  midi_cc: 77
  value: 40

