main_file: "LissajousZ"

midi_controllers:

 Volume:
  midi_cc: 7
  value: 64
 X Preset:
  midi_cc: 74
  value: '1'
  labels: [ '1', '2', '3', '4', '5', '6', '7', '8']
 Y Preset:
  midi_cc: 71
  value: '1'
  labels: [ '1', '2', '3', '4', '5', '6', '7', '8']
 Z Preset:
  midi_cc: 76
  value: '1'
  labels: [ '1', '2', '3', '4', '5', '6', '7', '8']
  
 X Color:
  midi_cc: 77
  value: 100
 Y Color:
  midi_cc: 93
  value: 64
 Z Color:
  midi_cc: 73
  value: 64
 Zoom:
  midi_cc: 75
  value: 64
  
 Speed:
  midi_cc: 114
  value: 20
 X Note:
  midi_cc: 18
  value: 20
 Y Note:
  midi_cc: 19
  value: 20
 Z Note:
  midi_cc: 16
  value: 20
  
 Mono Poly:
  midi_cc: 17
  value: '1'
  labels: [ '1', '2']
  
