main_file: "Spacezynth.pd"

midi_controllers:
 Master_Volume:
  midi_cc: 7
  value: 64
 Preset:
  midi_cc: 74
  value: '3'
  labels: [ '1', '2', '3', '4', '5', '6', '7', '8', '9', '10']
 Poly voices:
  midi_cc: 9
  value: 10
 Voice density:
  midi_cc: 10
  value: 5
 
 Res:
  midi_cc: 71
  value: 36
 Fr spac:
  midi_cc: 76
  value: 82
 Fr detune:
  midi_cc: 77
  value: 47
 Pan LFO:
  midi_cc: 93
  value: 107
  
 LFO spr:
  midi_cc: 73
  value: 0
 Hi fr Damp:
  midi_cc: 75
  value: 41
  
 Attack:
  midi_cc: 114
  value: 10
 Decay:
  midi_cc: 18
  value: 41
  
 Reverb Gain:
  midi_cc: 19
  value: 70
 Reverb Wet Dry:
  midi_cc: 16
  value: 60
 Reverb Room Size:
  midi_cc: 17
  value: 60
 Reverb Damp:
  midi_cc: 91
  value: 47
  
 Stereo Width:
  midi_cc: 79
  value: 80
 Retrigg:
  midi_cc: 72
  value: 7 
 Retrigg on/off:
  midi_cc: 11
  value: '0'
  labels: [ '0', '1']
 Randomize Patch:
  midi_cc: 12
  value: 0