main_file: "stepper.pd"

midi_controllers:
 Volume:
  midi_cc: 88
  value: 64
 Tempo:
  midi_cc: 89
  value: 120
 Slew:
  midi_cc: 90
  value: 4
 Steps:
  midi_cc: 91
  value: 8
  labels: [ '1', '2', '3', '4', '5', '6', '7', '8', '9', '10','11','12','13', '14','15','16']
  
 Step1:
  midi_cc: 92
  value: 50
 Step2:
  midi_cc: 93
  value: 50
 Step3:
  midi_cc: 94
  value: 50
 Step4:
  midi_cc: 95
  value: 50
  
 Step5:
  midi_cc: 96
  value: 50
 Step6:
  midi_cc: 97
  value: 50
 Step7:
  midi_cc: 98
  value: 50
 Step8:
  midi_cc: 99
  value: 50

 
 Step9:
  midi_cc: 100
  value: 50
 Step10:
  midi_cc: 101
  value: 50
 Step11:
  midi_cc: 102
  value: 50
 Step12:
  midi_cc: 103
  value: 50

 
 Step13:
  midi_cc: 104
  value: 50
 Step14:
  midi_cc: 105
  value: 50
 Step15:
  midi_cc: 106
  value: 50
 Step16:
  midi_cc: 107
  value: 50

