
main_file: "SYNTH-1.pd"

midi_controllers:
 volume:
  midi_cc: 7
  value: 70
 preset:
  midi_cc: 114
  value: '0'
  labels: [ '0', '1', '2', '3', '4', '5', '6', '7']
 filter_cutoff:
  midi_cc: 70
  value: 4
 filter_q:
  midi_cc: 71
  value: 13
  
 filtenv_A:
  midi_cc: 91
  value: 2
 filtenv_D:
  midi_cc: 93
  value: 4
 filtenv_S:
  midi_cc: 82
  value: 127
 filtenv_R:
  midi_cc: 83
  value: 0

 ampenv_A:
  midi_cc: 25
  value: 0
 ampenv_D:
  midi_cc: 26
  value: 0
 ampenv_S:
  midi_cc: 27
  value: 6
 ampenv_R:
  midi_cc: 28
  value: 3

 lfo_rate:
  midi_cc: 21
  value: 0
 lfo_depth:
  midi_cc: 22
  value: 0

 delay_time:
  midi_cc: 23
  value: 0
 delay_fb:
  midi_cc: 24
  value: 0
  
 Osc_mix:
  midi_cc: 72
  value: 50

 Osc1_fine:
  midi_cc: 73
  value: 0
 Osc2_fine:
  midi_cc: 3
  value: 0
 Save OFF/ON:
  midi_cc: 99
  value: '0'
  labels: [ '0', '1'] 
 