
main_file: "ZPM"

midi_controllers:
 Volume:
  midi_cc: 7
  value: 64
 MoreSlow:
  midi_cc: 3
  value: 0
  labels: ["OFF", "ON"]
  ticks: [0, 127]
 SoftPedal:
  midi_cc: 67
  value: 0
  labels: ["OFF", "ON"]
  ticks: [0, 127]
 FeltPedal:
  midi_cc: 69
  value: 127
  labels: ["OFF", "ON"]
  ticks: [0, 127]
 LHarp:
  midi_cc: 28
  value: 127
  labels: ["OFF", "ON"]
  ticks: [0, 127]
 LHrndmzr:
  midi_cc: 29
  value: 0
  labels: ["OFF", "ON"]
  ticks: [0, 127]
 RHarp:
  midi_cc: 30
  value: 127
  labels: ["OFF", "ON"]
  ticks: [0, 127]
 RHrndmzr:
  midi_cc: 31
  value: 0
  labels: ["OFF", "ON"]
  ticks: [0, 127]

