main_file: "Zynscope"

midi_controllers:
 Wave Size:
  midi_cc: 74
  value: 50
 Window Size:
  midi_cc: 71
  value: 10
 X Position:
  midi_cc: 76
  value: 40
 Y Position:
  midi_cc: 77
  value: 40



